# Generated by Django 5.1.7 on 2025-03-29 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('discount_percentage', models.IntegerField()),
                ('valid_until', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_id', models.AutoField(primary_key=True, serialize=False)),
                ('airline', models.CharField(max_length=100)),
                ('departure_location', models.CharField(max_length=100)),
                ('destination_location', models.CharField(max_length=100)),
                ('destination_time', models.DateTimeField()),
                ('departure_time', models.DateField()),
                ('available_seats', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airlineapp.flight')),
            ],
        ),
        migrations.CreateModel(
            name='ReserVation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=100)),
                ('seat_number', models.CharField(max_length=5, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('paid_price', models.IntegerField(default=False)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airlineapp.flight')),
            ],
        ),
    ]
