# Generated by Django 3.2.25 on 2025-03-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlineapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='paid_price',
            field=models.FloatField(default=False),
        ),
    ]
