# Generated by Django 5.1.7 on 2025-03-29 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlineapp', '0002_alter_reservation_paid_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.DateTimeField(),
        ),
    ]
